const DAILY_QUOTES = [
  { text: "The only bad workout is the one that didn't happen.", author: "Unknown" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "David Goggins" },
  { text: "The body achieves what the mind believes.", author: "Napoleon Hill" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
  { text: "It never gets easier. You just get stronger.", author: "Unknown" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "Be stronger than your excuses.", author: "Unknown" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
  { text: "One day or day one. You decide.", author: "Unknown" },
  { text: "Obsessed is a word the lazy use to describe the dedicated.", author: "Unknown" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "Fall in love with the process and the results will come.", author: "Eric Thomas" },
  { text: "Show up. Every single day.", author: "Unknown" },
  { text: "Consistency beats intensity. Every time.", author: "Unknown" },
  { text: "You never regret a workout.", author: "Unknown" },
  { text: "What seems impossible today will one day become your warm-up.", author: "Unknown" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "A year from now you'll wish you had started today.", author: "Karen Lamb" },
  { text: "The difference between who you are and who you want to be is what you do.", author: "Unknown" },
  { text: "Earn it.", author: "Unknown" },
  { text: "Champions are made from something deep inside.", author: "Muhammad Ali" },
  { text: "Your only limit is you.", author: "Unknown" },
  { text: "Train insane or remain the same.", author: "Unknown" },
  { text: "Push yourself because no one else is going to do it for you.", author: "Unknown" },
  { text: "Results happen over time, not overnight. Work hard, stay consistent.", author: "Unknown" },
  { text: "No matter how slow you go, you are still lapping everybody on the couch.", author: "Unknown" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "You don't get what you wish for. You get what you work for.", author: "Unknown" },
  { text: "Every rep, every set, every drop of sweat is building the best version of you.", author: "Unknown" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Gandhi" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin" },
  { text: "Your health is an investment, not an expense.", author: "Unknown" },
  { text: "Do what you have to do, until you can do what you want to do.", author: "Oprah Winfrey" },
  { text: "The gym is not a punishment. It's a privilege.", author: "Unknown" },
  { text: "You are stronger than you think.", author: "Unknown" },
  { text: "Act like a champion. Train like a champion. Be a champion.", author: "Unknown" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "The pain of discipline is far less than the pain of regret.", author: "Unknown" },
  { text: "First, master the fundamentals.", author: "Larry Bird" },
  { text: "Small steps in the right direction beat giant leaps in the wrong one.", author: "Unknown" },
  { text: "Every champion was once a contender who refused to give up.", author: "Unknown" },
  { text: "You've got what it takes, but it will take everything you've got.", author: "Unknown" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "Work hard in silence. Let success be your noise.", author: "Frank Ocean" },
  { text: "You are your only limit.", author: "Unknown" },
  { text: "Keep going. Your hardest times lead to the greatest moments.", author: "Roy T. Bennett" },
  { text: "The body keeps the score. Make sure yours is winning.", author: "Unknown" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Sweat is just fat crying.", author: "Unknown" },
  { text: "Fit is not a destination. It is a way of life.", author: "Unknown" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "Don't limit your challenges. Challenge your limits.", author: "Jerry Dunn" },
  { text: "You have to expect things of yourself before you can do them.", author: "Michael Jordan" },
  { text: "The best time to start was yesterday. The next best time is now.", author: "Unknown" },
  { text: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito" },
  { text: "Your future self is watching you right now through your memories.", author: "Aubrey Marcus" },
  { text: "Hard days are the best because that is when champions are made.", author: "Gabby Douglas" },
  { text: "When you feel like quitting, think about why you started.", author: "Unknown" },
  { text: "Don't wish for it. Work for it.", author: "Unknown" },
  { text: "The grind never stops.", author: "Unknown" },
];

const GOAL_TYPES = {
  weight_loss:  { label: 'Weight Loss',  icon: '↓', desc: 'Lose fat & get leaner',        metric: 'lower_weight' },
  weight_gain:  { label: 'Weight Gain',  icon: '↑', desc: 'Build mass & get bigger',       metric: 'higher_weight' },
  recomp:       { label: 'Body Recomp',  icon: '⇄', desc: 'Lose fat, gain muscle',         metric: 'consistency' },
  endurance:    { label: 'Endurance',    icon: '⟳', desc: 'Run longer & build stamina',    metric: 'higher_steps' },
  strength:     { label: 'Strength',     icon: '◆', desc: 'Get stronger & PR on lifts',    metric: 'consistency' },
  maintenance:  { label: 'Maintenance',  icon: '—', desc: 'Stay consistent & healthy',      metric: 'consistency' },
};

module.exports = { DAILY_QUOTES, GOAL_TYPES };
