// qawi-food-db.jsx — Curated food database with accurate macros
// All macros per listed serving. Sources: USDA FoodData Central, Nutritionix.
// Halal-aware; covers MENA, South Asian, Southeast Asian, Turkish, and Western staples.

window.QAWI_FOODS = [
  // ============== PROTEINS — MEAT & POULTRY ==============
  { id: 'chicken-breast',    name: 'Chicken Breast (Grilled)',   cat: 'protein', serving: 100, unit: 'g', cal: 165, p: 31,   c: 0,    f: 3.6,  fiber: 0 },
  { id: 'chicken-thigh',     name: 'Chicken Thigh (Grilled)',    cat: 'protein', serving: 100, unit: 'g', cal: 209, p: 26,   c: 0,    f: 10.9, fiber: 0 },
  { id: 'chicken-wing',      name: 'Chicken Wing (Roasted)',     cat: 'protein', serving: 100, unit: 'g', cal: 290, p: 27,   c: 0,    f: 19.5, fiber: 0 },
  { id: 'ground-beef-lean',  name: 'Ground Beef (93% Lean)',     cat: 'protein', serving: 100, unit: 'g', cal: 152, p: 21,   c: 0,    f: 7,    fiber: 0 },
  { id: 'ground-beef-reg',   name: 'Ground Beef (80% Lean)',     cat: 'protein', serving: 100, unit: 'g', cal: 254, p: 17,   c: 0,    f: 20,   fiber: 0 },
  { id: 'ribeye',            name: 'Ribeye Steak',               cat: 'protein', serving: 100, unit: 'g', cal: 291, p: 24,   c: 0,    f: 22,   fiber: 0 },
  { id: 'sirloin',           name: 'Sirloin Steak',              cat: 'protein', serving: 100, unit: 'g', cal: 206, p: 29,   c: 0,    f: 9,    fiber: 0 },
  { id: 'lamb-chop',         name: 'Lamb Chop',                  cat: 'protein', serving: 100, unit: 'g', cal: 294, p: 25,   c: 0,    f: 21,   fiber: 0 },
  { id: 'lamb-ground',       name: 'Ground Lamb',                cat: 'protein', serving: 100, unit: 'g', cal: 282, p: 25,   c: 0,    f: 19.7, fiber: 0 },
  { id: 'turkey-breast',     name: 'Turkey Breast',              cat: 'protein', serving: 100, unit: 'g', cal: 135, p: 30,   c: 0,    f: 1,    fiber: 0 },
  { id: 'turkey-ground',     name: 'Ground Turkey (93%)',        cat: 'protein', serving: 100, unit: 'g', cal: 176, p: 22,   c: 0,    f: 10,   fiber: 0 },
  { id: 'veal',              name: 'Veal',                       cat: 'protein', serving: 100, unit: 'g', cal: 172, p: 30,   c: 0,    f: 5,    fiber: 0 },
  { id: 'beef-liver',        name: 'Beef Liver',                 cat: 'protein', serving: 100, unit: 'g', cal: 175, p: 27,   c: 4,    f: 5,    fiber: 0 },

  // ============== PROTEINS — FISH & SEAFOOD ==============
  { id: 'salmon',            name: 'Salmon (Baked)',             cat: 'protein', serving: 100, unit: 'g', cal: 206, p: 22,   c: 0,    f: 13,   fiber: 0 },
  { id: 'tuna-canned',       name: 'Tuna (Canned in Water)',     cat: 'protein', serving: 100, unit: 'g', cal: 116, p: 26,   c: 0,    f: 1,    fiber: 0 },
  { id: 'tuna-steak',        name: 'Tuna Steak',                 cat: 'protein', serving: 100, unit: 'g', cal: 184, p: 30,   c: 0,    f: 6,    fiber: 0 },
  { id: 'tilapia',           name: 'Tilapia',                    cat: 'protein', serving: 100, unit: 'g', cal: 128, p: 26,   c: 0,    f: 2.7,  fiber: 0 },
  { id: 'cod',               name: 'Cod (Baked)',                cat: 'protein', serving: 100, unit: 'g', cal: 105, p: 23,   c: 0,    f: 0.9,  fiber: 0 },
  { id: 'sardines',          name: 'Sardines (Canned)',          cat: 'protein', serving: 100, unit: 'g', cal: 208, p: 25,   c: 0,    f: 11,   fiber: 0 },
  { id: 'shrimp',            name: 'Shrimp (Cooked)',            cat: 'protein', serving: 100, unit: 'g', cal: 99,  p: 24,   c: 0.2,  f: 0.3,  fiber: 0 },
  { id: 'mackerel',          name: 'Mackerel',                   cat: 'protein', serving: 100, unit: 'g', cal: 205, p: 19,   c: 0,    f: 14,   fiber: 0 },
  { id: 'sea-bass',          name: 'Sea Bass',                   cat: 'protein', serving: 100, unit: 'g', cal: 124, p: 24,   c: 0,    f: 2.6,  fiber: 0 },

  // ============== PROTEINS — EGGS & DAIRY ==============
  { id: 'egg-whole',         name: 'Egg (Whole, Large)',         cat: 'protein', serving: 1,   unit: 'ea', cal: 72, p: 6.3,  c: 0.4,  f: 4.8,  fiber: 0 },
  { id: 'egg-white',         name: 'Egg White',                  cat: 'protein', serving: 1,   unit: 'ea', cal: 17, p: 3.6,  c: 0.2,  f: 0.1,  fiber: 0 },
  { id: 'greek-yogurt',      name: 'Greek Yogurt (Plain, 0%)',   cat: 'protein', serving: 170, unit: 'g', cal: 100, p: 17,   c: 6,    f: 0.7,  fiber: 0 },
  { id: 'greek-yogurt-full', name: 'Greek Yogurt (Full Fat)',    cat: 'protein', serving: 170, unit: 'g', cal: 158, p: 14,   c: 7,    f: 8,    fiber: 0 },
  { id: 'cottage-cheese',    name: 'Cottage Cheese (Low-Fat)',   cat: 'protein', serving: 100, unit: 'g', cal: 84,  p: 11,   c: 4,    f: 2.3,  fiber: 0 },
  { id: 'labneh',            name: 'Labneh',                     cat: 'protein', serving: 100, unit: 'g', cal: 168, p: 10,   c: 4,    f: 13,   fiber: 0 },
  { id: 'milk-whole',        name: 'Milk (Whole)',               cat: 'protein', serving: 240, unit: 'ml', cal: 149, p: 8,    c: 12,   f: 8,    fiber: 0 },
  { id: 'milk-skim',         name: 'Milk (Skim)',                cat: 'protein', serving: 240, unit: 'ml', cal: 83,  p: 8,    c: 12,   f: 0.2,  fiber: 0 },
  { id: 'milk-almond',       name: 'Almond Milk (Unsweetened)',  cat: 'protein', serving: 240, unit: 'ml', cal: 30,  p: 1,    c: 1,    f: 2.5,  fiber: 0.5 },
  { id: 'cheddar',           name: 'Cheddar Cheese',             cat: 'protein', serving: 28,  unit: 'g', cal: 113, p: 7,    c: 0.4,  f: 9.3,  fiber: 0 },
  { id: 'mozzarella',        name: 'Mozzarella',                 cat: 'protein', serving: 28,  unit: 'g', cal: 85,  p: 6.3,  c: 0.6,  f: 6.3,  fiber: 0 },
  { id: 'feta',              name: 'Feta Cheese',                cat: 'protein', serving: 28,  unit: 'g', cal: 75,  p: 4,    c: 1.2,  f: 6,    fiber: 0 },
  { id: 'halloumi',          name: 'Halloumi',                   cat: 'protein', serving: 28,  unit: 'g', cal: 88,  p: 6,    c: 1,    f: 7,    fiber: 0 },

  // ============== PROTEINS — PLANT-BASED ==============
  { id: 'tofu-firm',         name: 'Tofu (Firm)',                cat: 'protein', serving: 100, unit: 'g', cal: 144, p: 17,   c: 3,    f: 9,    fiber: 2 },
  { id: 'tempeh',            name: 'Tempeh',                     cat: 'protein', serving: 100, unit: 'g', cal: 193, p: 20,   c: 9,    f: 11,   fiber: 0 },
  { id: 'edamame',           name: 'Edamame (Shelled)',          cat: 'protein', serving: 100, unit: 'g', cal: 121, p: 12,   c: 9,    f: 5,    fiber: 5 },
  { id: 'chickpeas',         name: 'Chickpeas (Cooked)',         cat: 'protein', serving: 100, unit: 'g', cal: 164, p: 9,    c: 27,   f: 2.6,  fiber: 8 },
  { id: 'lentils',           name: 'Lentils (Cooked)',           cat: 'protein', serving: 100, unit: 'g', cal: 116, p: 9,    c: 20,   f: 0.4,  fiber: 8 },
  { id: 'black-beans',       name: 'Black Beans (Cooked)',       cat: 'protein', serving: 100, unit: 'g', cal: 132, p: 9,    c: 24,   f: 0.5,  fiber: 8.7 },
  { id: 'kidney-beans',      name: 'Kidney Beans (Cooked)',      cat: 'protein', serving: 100, unit: 'g', cal: 127, p: 8.7,  c: 23,   f: 0.5,  fiber: 6.4 },
  { id: 'fava-beans',        name: 'Fava Beans (Cooked)',        cat: 'protein', serving: 100, unit: 'g', cal: 110, p: 7.6,  c: 20,   f: 0.4,  fiber: 5 },

  // ============== PROTEIN SUPPLEMENTS ==============
  { id: 'whey-scoop',        name: 'Whey Protein (Scoop)',       cat: 'supplement', serving: 30, unit: 'g', cal: 120, p: 24, c: 3,    f: 1.5,  fiber: 0 },
  { id: 'casein-scoop',      name: 'Casein Protein (Scoop)',     cat: 'supplement', serving: 32, unit: 'g', cal: 120, p: 24, c: 3,    f: 1,    fiber: 0 },
  { id: 'protein-bar',       name: 'Protein Bar (Generic)',      cat: 'supplement', serving: 60, unit: 'g', cal: 220, p: 20, c: 22,   f: 8,    fiber: 5 },
  { id: 'pre-workout',       name: 'Pre-Workout (Scoop)',        cat: 'supplement', serving: 10, unit: 'g', cal: 10,  p: 0,  c: 2,    f: 0,    fiber: 0 },

  // ============== CARBS — GRAINS & STARCHES ==============
  { id: 'rice-white',        name: 'White Rice (Cooked)',        cat: 'carb',    serving: 100, unit: 'g', cal: 130, p: 2.7,  c: 28,   f: 0.3,  fiber: 0.4 },
  { id: 'rice-brown',        name: 'Brown Rice (Cooked)',        cat: 'carb',    serving: 100, unit: 'g', cal: 112, p: 2.6,  c: 24,   f: 0.9,  fiber: 1.8 },
  { id: 'rice-basmati',      name: 'Basmati Rice (Cooked)',      cat: 'carb',    serving: 100, unit: 'g', cal: 121, p: 3,    c: 25,   f: 0.4,  fiber: 0.4 },
  { id: 'jasmine-rice',      name: 'Jasmine Rice (Cooked)',      cat: 'carb',    serving: 100, unit: 'g', cal: 129, p: 2.7,  c: 28,   f: 0.2,  fiber: 0.6 },
  { id: 'quinoa',            name: 'Quinoa (Cooked)',            cat: 'carb',    serving: 100, unit: 'g', cal: 120, p: 4.4,  c: 21,   f: 1.9,  fiber: 2.8 },
  { id: 'oats',              name: 'Oats (Dry)',                 cat: 'carb',    serving: 40,  unit: 'g', cal: 152, p: 5.3,  c: 27,   f: 2.6,  fiber: 4 },
  { id: 'oatmeal-cooked',    name: 'Oatmeal (Cooked, Water)',    cat: 'carb',    serving: 234, unit: 'g', cal: 158, p: 6,    c: 27,   f: 3,    fiber: 4 },
  { id: 'couscous',          name: 'Couscous (Cooked)',          cat: 'carb',    serving: 100, unit: 'g', cal: 112, p: 3.8,  c: 23,   f: 0.2,  fiber: 1.4 },
  { id: 'bulgur',            name: 'Bulgur (Cooked)',            cat: 'carb',    serving: 100, unit: 'g', cal: 83,  p: 3,    c: 18.6, f: 0.2,  fiber: 4.5 },
  { id: 'freekeh',           name: 'Freekeh (Cooked)',           cat: 'carb',    serving: 100, unit: 'g', cal: 101, p: 5,    c: 20,   f: 0.6,  fiber: 5 },
  { id: 'pasta',             name: 'Pasta (Cooked)',             cat: 'carb',    serving: 100, unit: 'g', cal: 131, p: 5,    c: 25,   f: 1.1,  fiber: 1.8 },
  { id: 'whole-wheat-pasta', name: 'Whole Wheat Pasta (Cooked)', cat: 'carb',    serving: 100, unit: 'g', cal: 124, p: 5,    c: 26,   f: 0.5,  fiber: 3.2 },
  { id: 'bread-white',       name: 'White Bread (Slice)',        cat: 'carb',    serving: 1,   unit: 'slice', cal: 76, p: 2.6, c: 14, f: 1,    fiber: 0.8 },
  { id: 'bread-wheat',       name: 'Whole Wheat Bread (Slice)',  cat: 'carb',    serving: 1,   unit: 'slice', cal: 81, p: 4,   c: 14, f: 1.1,  fiber: 1.9 },
  { id: 'sourdough',         name: 'Sourdough Bread (Slice)',    cat: 'carb',    serving: 1,   unit: 'slice', cal: 93, p: 4,   c: 18, f: 0.6,  fiber: 0.7 },
  { id: 'pita',              name: 'Pita Bread (Whole)',         cat: 'carb',    serving: 1,   unit: 'ea', cal: 165, p: 5.5,  c: 33,   f: 0.7,  fiber: 1.3 },
  { id: 'pita-wheat',        name: 'Whole Wheat Pita',           cat: 'carb',    serving: 1,   unit: 'ea', cal: 170, p: 6.3,  c: 35,   f: 1.7,  fiber: 4.7 },
  { id: 'naan',              name: 'Naan Bread',                 cat: 'carb',    serving: 1,   unit: 'ea', cal: 262, p: 9,    c: 45,   f: 5,    fiber: 2 },
  { id: 'roti',              name: 'Roti (Whole Wheat)',         cat: 'carb',    serving: 1,   unit: 'ea', cal: 120, p: 3,    c: 23,   f: 2.5,  fiber: 3 },
  { id: 'paratha',           name: 'Paratha',                    cat: 'carb',    serving: 1,   unit: 'ea', cal: 200, p: 4.5,  c: 26,   f: 9,    fiber: 3 },
  { id: 'tortilla-flour',    name: 'Flour Tortilla',             cat: 'carb',    serving: 1,   unit: 'ea', cal: 138, p: 3.7,  c: 22,   f: 3.7,  fiber: 1.3 },
  { id: 'tortilla-corn',     name: 'Corn Tortilla',              cat: 'carb',    serving: 1,   unit: 'ea', cal: 50,  p: 1.3,  c: 10.7, f: 0.7,  fiber: 1.5 },
  { id: 'bagel',             name: 'Bagel (Plain)',              cat: 'carb',    serving: 1,   unit: 'ea', cal: 245, p: 10,   c: 48,   f: 1.5,  fiber: 2 },
  { id: 'english-muffin',    name: 'English Muffin',             cat: 'carb',    serving: 1,   unit: 'ea', cal: 134, p: 4.4,  c: 26,   f: 1,    fiber: 1.5 },
  { id: 'cereal-granola',    name: 'Granola',                    cat: 'carb',    serving: 60,  unit: 'g', cal: 280, p: 6,    c: 42,   f: 10,   fiber: 5 },
  { id: 'cereal-bran',       name: 'Bran Flakes',                cat: 'carb',    serving: 40,  unit: 'g', cal: 128, p: 4,    c: 31,   f: 1,    fiber: 7 },

  // ============== CARBS — POTATOES & STARCHY VEG ==============
  { id: 'potato',            name: 'Potato (Baked, with Skin)',  cat: 'carb',    serving: 100, unit: 'g', cal: 93,  p: 2.5,  c: 21,   f: 0.1,  fiber: 2.2 },
  { id: 'sweet-potato',      name: 'Sweet Potato (Baked)',       cat: 'carb',    serving: 100, unit: 'g', cal: 90,  p: 2,    c: 21,   f: 0.2,  fiber: 3.3 },
  { id: 'fries',             name: 'French Fries',               cat: 'carb',    serving: 100, unit: 'g', cal: 312, p: 3.4,  c: 41,   f: 15,   fiber: 3.8 },

  // ============== FRUITS ==============
  { id: 'apple',             name: 'Apple (Medium)',             cat: 'fruit',   serving: 1,   unit: 'ea', cal: 95, p: 0.5,  c: 25,   f: 0.3,  fiber: 4.4 },
  { id: 'banana',            name: 'Banana (Medium)',            cat: 'fruit',   serving: 1,   unit: 'ea', cal: 105,p: 1.3,  c: 27,   f: 0.4,  fiber: 3 },
  { id: 'orange',            name: 'Orange (Medium)',            cat: 'fruit',   serving: 1,   unit: 'ea', cal: 62, p: 1.2,  c: 15,   f: 0.2,  fiber: 3 },
  { id: 'strawberries',      name: 'Strawberries',               cat: 'fruit',   serving: 100, unit: 'g', cal: 32, p: 0.7,  c: 7.7,  f: 0.3,  fiber: 2 },
  { id: 'blueberries',       name: 'Blueberries',                cat: 'fruit',   serving: 100, unit: 'g', cal: 57, p: 0.7,  c: 14,   f: 0.3,  fiber: 2.4 },
  { id: 'grapes',            name: 'Grapes',                     cat: 'fruit',   serving: 100, unit: 'g', cal: 69, p: 0.7,  c: 18,   f: 0.2,  fiber: 0.9 },
  { id: 'mango',             name: 'Mango',                      cat: 'fruit',   serving: 100, unit: 'g', cal: 60, p: 0.8,  c: 15,   f: 0.4,  fiber: 1.6 },
  { id: 'pineapple',         name: 'Pineapple',                  cat: 'fruit',   serving: 100, unit: 'g', cal: 50, p: 0.5,  c: 13,   f: 0.1,  fiber: 1.4 },
  { id: 'watermelon',        name: 'Watermelon',                 cat: 'fruit',   serving: 100, unit: 'g', cal: 30, p: 0.6,  c: 7.6,  f: 0.2,  fiber: 0.4 },
  { id: 'dates-medjool',     name: 'Medjool Dates',              cat: 'fruit',   serving: 1,   unit: 'ea', cal: 66, p: 0.4,  c: 18,   f: 0,    fiber: 1.6 },
  { id: 'dates-deglet',      name: 'Deglet Noor Dates',          cat: 'fruit',   serving: 1,   unit: 'ea', cal: 20, p: 0.2,  c: 5.3,  f: 0,    fiber: 0.6 },
  { id: 'figs',              name: 'Figs (Fresh)',               cat: 'fruit',   serving: 1,   unit: 'ea', cal: 37, p: 0.4,  c: 9.6,  f: 0.2,  fiber: 1.4 },
  { id: 'pomegranate',       name: 'Pomegranate Seeds',          cat: 'fruit',   serving: 100, unit: 'g', cal: 83, p: 1.7,  c: 19,   f: 1.2,  fiber: 4 },
  { id: 'avocado',           name: 'Avocado (Half)',             cat: 'fat',     serving: 1,   unit: 'ea half', cal: 161, p: 2, c: 8.5, f: 15, fiber: 6.7 },
  { id: 'peach',             name: 'Peach',                      cat: 'fruit',   serving: 1,   unit: 'ea', cal: 59, p: 1.4,  c: 14,   f: 0.4,  fiber: 2.3 },
  { id: 'pear',              name: 'Pear',                       cat: 'fruit',   serving: 1,   unit: 'ea', cal: 101,p: 0.6,  c: 27,   f: 0.3,  fiber: 5.5 },

  // ============== VEGETABLES ==============
  { id: 'broccoli',          name: 'Broccoli (Steamed)',         cat: 'veg',     serving: 100, unit: 'g', cal: 35, p: 2.4,  c: 7,    f: 0.4,  fiber: 3.3 },
  { id: 'spinach',           name: 'Spinach',                    cat: 'veg',     serving: 100, unit: 'g', cal: 23, p: 2.9,  c: 3.6,  f: 0.4,  fiber: 2.2 },
  { id: 'kale',              name: 'Kale',                       cat: 'veg',     serving: 100, unit: 'g', cal: 49, p: 4.3,  c: 9,    f: 0.9,  fiber: 3.6 },
  { id: 'carrot',            name: 'Carrot (Medium)',            cat: 'veg',     serving: 1,   unit: 'ea', cal: 25, p: 0.6,  c: 6,    f: 0.1,  fiber: 1.7 },
  { id: 'cucumber',          name: 'Cucumber',                   cat: 'veg',     serving: 100, unit: 'g', cal: 15, p: 0.7,  c: 3.6,  f: 0.1,  fiber: 0.5 },
  { id: 'tomato',            name: 'Tomato (Medium)',            cat: 'veg',     serving: 1,   unit: 'ea', cal: 22, p: 1.1,  c: 4.8,  f: 0.2,  fiber: 1.5 },
  { id: 'lettuce',           name: 'Lettuce (Romaine)',          cat: 'veg',     serving: 100, unit: 'g', cal: 17, p: 1.2,  c: 3.3,  f: 0.3,  fiber: 2.1 },
  { id: 'bell-pepper',       name: 'Bell Pepper',                cat: 'veg',     serving: 1,   unit: 'ea', cal: 37, p: 1.2,  c: 7.2,  f: 0.4,  fiber: 2.5 },
  { id: 'onion',             name: 'Onion',                      cat: 'veg',     serving: 100, unit: 'g', cal: 40, p: 1.1,  c: 9.3,  f: 0.1,  fiber: 1.7 },
  { id: 'garlic',            name: 'Garlic',                     cat: 'veg',     serving: 1,   unit: 'clove', cal: 4, p: 0.2, c: 1, f: 0,    fiber: 0.1 },
  { id: 'mushrooms',         name: 'Mushrooms',                  cat: 'veg',     serving: 100, unit: 'g', cal: 22, p: 3.1,  c: 3.3,  f: 0.3,  fiber: 1 },
  { id: 'zucchini',          name: 'Zucchini',                   cat: 'veg',     serving: 100, unit: 'g', cal: 17, p: 1.2,  c: 3.1,  f: 0.3,  fiber: 1 },
  { id: 'eggplant',          name: 'Eggplant',                   cat: 'veg',     serving: 100, unit: 'g', cal: 25, p: 1,    c: 6,    f: 0.2,  fiber: 3 },
  { id: 'cauliflower',       name: 'Cauliflower',                cat: 'veg',     serving: 100, unit: 'g', cal: 25, p: 1.9,  c: 5,    f: 0.3,  fiber: 2 },
  { id: 'green-beans',       name: 'Green Beans',                cat: 'veg',     serving: 100, unit: 'g', cal: 31, p: 1.8,  c: 7,    f: 0.2,  fiber: 2.7 },
  { id: 'asparagus',         name: 'Asparagus',                  cat: 'veg',     serving: 100, unit: 'g', cal: 20, p: 2.2,  c: 3.9,  f: 0.1,  fiber: 2.1 },
  { id: 'corn',              name: 'Corn (Sweet)',               cat: 'veg',     serving: 100, unit: 'g', cal: 86, p: 3.2,  c: 19,   f: 1.2,  fiber: 2.7 },
  { id: 'okra',              name: 'Okra',                       cat: 'veg',     serving: 100, unit: 'g', cal: 33, p: 2,    c: 7,    f: 0.2,  fiber: 3.2 },
  { id: 'cabbage',           name: 'Cabbage',                    cat: 'veg',     serving: 100, unit: 'g', cal: 25, p: 1.3,  c: 5.8,  f: 0.1,  fiber: 2.5 },

  // ============== FATS — NUTS, SEEDS, OILS ==============
  { id: 'almonds',           name: 'Almonds',                    cat: 'fat',     serving: 28,  unit: 'g', cal: 164, p: 6,    c: 6,    f: 14,   fiber: 3.5 },
  { id: 'walnuts',           name: 'Walnuts',                    cat: 'fat',     serving: 28,  unit: 'g', cal: 185, p: 4.3,  c: 3.9,  f: 18.5, fiber: 1.9 },
  { id: 'cashews',           name: 'Cashews',                    cat: 'fat',     serving: 28,  unit: 'g', cal: 157, p: 5,    c: 9,    f: 12,   fiber: 0.9 },
  { id: 'pistachios',        name: 'Pistachios',                 cat: 'fat',     serving: 28,  unit: 'g', cal: 159, p: 5.7,  c: 8,    f: 12.8, fiber: 3 },
  { id: 'peanuts',           name: 'Peanuts',                    cat: 'fat',     serving: 28,  unit: 'g', cal: 161, p: 7,    c: 4.6,  f: 14,   fiber: 2.4 },
  { id: 'peanut-butter',     name: 'Peanut Butter (Tbsp)',       cat: 'fat',     serving: 1,   unit: 'tbsp', cal: 94, p: 4, c: 3.1,   f: 8,    fiber: 0.9 },
  { id: 'almond-butter',     name: 'Almond Butter (Tbsp)',       cat: 'fat',     serving: 1,   unit: 'tbsp', cal: 98, p: 3.4, c: 3, f: 9, fiber: 1.6 },
  { id: 'mixed-nuts',        name: 'Mixed Nuts',                 cat: 'fat',     serving: 28,  unit: 'g', cal: 172, p: 5,    c: 6,    f: 15,   fiber: 2.6 },
  { id: 'chia-seeds',        name: 'Chia Seeds (Tbsp)',          cat: 'fat',     serving: 1,   unit: 'tbsp', cal: 60, p: 2, c: 5, f: 4, fiber: 4 },
  { id: 'flax-seeds',        name: 'Flax Seeds (Tbsp)',          cat: 'fat',     serving: 1,   unit: 'tbsp', cal: 37, p: 1.3, c: 2, f: 3, fiber: 1.9 },
  { id: 'olive-oil',         name: 'Olive Oil (Tbsp)',           cat: 'fat',     serving: 1,   unit: 'tbsp', cal: 119, p: 0, c: 0, f: 13.5, fiber: 0 },
  { id: 'butter',            name: 'Butter (Tbsp)',              cat: 'fat',     serving: 1,   unit: 'tbsp', cal: 102, p: 0.1, c: 0, f: 11.5, fiber: 0 },
  { id: 'ghee',              name: 'Ghee (Tbsp)',                cat: 'fat',     serving: 1,   unit: 'tbsp', cal: 112, p: 0, c: 0, f: 12.7, fiber: 0 },
  { id: 'coconut-oil',       name: 'Coconut Oil (Tbsp)',         cat: 'fat',     serving: 1,   unit: 'tbsp', cal: 117, p: 0, c: 0, f: 13.6, fiber: 0 },
  { id: 'tahini',            name: 'Tahini (Tbsp)',              cat: 'fat',     serving: 1,   unit: 'tbsp', cal: 89, p: 2.6, c: 3.2, f: 8, fiber: 1.4 },

  // ============== MIDDLE EASTERN DISHES ==============
  { id: 'shawarma-chicken',  name: 'Chicken Shawarma Wrap',      cat: 'meal',    serving: 1,   unit: 'wrap', cal: 530, p: 35, c: 45, f: 22, fiber: 4 },
  { id: 'shawarma-beef',     name: 'Beef Shawarma Wrap',         cat: 'meal',    serving: 1,   unit: 'wrap', cal: 620, p: 38, c: 45, f: 30, fiber: 4 },
  { id: 'shawarma-plate',    name: 'Shawarma Plate (Chicken)',   cat: 'meal',    serving: 1,   unit: 'plate', cal: 780, p: 52, c: 70, f: 28, fiber: 5 },
  { id: 'falafel',           name: 'Falafel Ball',               cat: 'meal',    serving: 1,   unit: 'ea', cal: 57, p: 2.3,  c: 5.4,  f: 3,    fiber: 0.9 },
  { id: 'falafel-wrap',      name: 'Falafel Wrap',               cat: 'meal',    serving: 1,   unit: 'wrap', cal: 440, p: 15, c: 62, f: 16, fiber: 9 },
  { id: 'hummus',            name: 'Hummus (2 Tbsp)',            cat: 'meal',    serving: 2,   unit: 'tbsp', cal: 70, p: 2,   c: 6,    f: 4,    fiber: 2 },
  { id: 'hummus-plate',      name: 'Hummus Plate with Pita',     cat: 'meal',    serving: 1,   unit: 'plate', cal: 450, p: 14, c: 58, f: 18, fiber: 10 },
  { id: 'baba-ganoush',      name: 'Baba Ganoush (2 Tbsp)',      cat: 'meal',    serving: 2,   unit: 'tbsp', cal: 70, p: 1.5, c: 4,    f: 5.6,  fiber: 1.5 },
  { id: 'tabbouleh',         name: 'Tabbouleh (1 cup)',          cat: 'meal',    serving: 1,   unit: 'cup', cal: 170, p: 3,   c: 20,   f: 10,   fiber: 4 },
  { id: 'fattoush',          name: 'Fattoush Salad',             cat: 'meal',    serving: 1,   unit: 'bowl', cal: 220, p: 5,  c: 22,   f: 13,   fiber: 4 },
  { id: 'foul',              name: 'Foul Medames (Plate)',       cat: 'meal',    serving: 1,   unit: 'plate', cal: 280, p: 16, c: 40, f: 7, fiber: 14 },
  { id: 'koshari',           name: 'Koshari (Plate)',            cat: 'meal',    serving: 1,   unit: 'plate', cal: 680, p: 22, c: 120, f: 12, fiber: 15 },
  { id: 'molokhia',          name: 'Molokhia (Bowl)',            cat: 'meal',    serving: 1,   unit: 'bowl', cal: 180, p: 10, c: 14,   f: 9,    fiber: 4 },
  { id: 'kofta',             name: 'Kofta (Beef, 2 Skewers)',    cat: 'meal',    serving: 2,   unit: 'skewers', cal: 480, p: 32, c: 6, f: 36, fiber: 1 },
  { id: 'kebab-chicken',     name: 'Chicken Kebab (Skewer)',     cat: 'meal',    serving: 1,   unit: 'skewer', cal: 220, p: 28, c: 2, f: 11, fiber: 0 },
  { id: 'kebab-beef',        name: 'Beef Kebab (Skewer)',        cat: 'meal',    serving: 1,   unit: 'skewer', cal: 270, p: 26, c: 2, f: 17, fiber: 0 },
  { id: 'mandi-chicken',     name: 'Chicken Mandi (Plate)',      cat: 'meal',    serving: 1,   unit: 'plate', cal: 780, p: 45, c: 90, f: 26, fiber: 3 },
  { id: 'mandi-lamb',        name: 'Lamb Mandi (Plate)',         cat: 'meal',    serving: 1,   unit: 'plate', cal: 920, p: 48, c: 90, f: 38, fiber: 3 },
  { id: 'kabsa',             name: 'Kabsa (Plate)',              cat: 'meal',    serving: 1,   unit: 'plate', cal: 720, p: 40, c: 85, f: 25, fiber: 3 },
  { id: 'machboos',          name: 'Machboos (Plate)',           cat: 'meal',    serving: 1,   unit: 'plate', cal: 750, p: 42, c: 82, f: 28, fiber: 3 },
  { id: 'harees',            name: 'Harees (Bowl)',              cat: 'meal',    serving: 1,   unit: 'bowl', cal: 420, p: 28, c: 45, f: 13, fiber: 4 },
  { id: 'mansaf',            name: 'Mansaf (Plate)',             cat: 'meal',    serving: 1,   unit: 'plate', cal: 820, p: 45, c: 80, f: 32, fiber: 3 },
  { id: 'maqluba',           name: 'Maqluba (Plate)',            cat: 'meal',    serving: 1,   unit: 'plate', cal: 650, p: 30, c: 80, f: 22, fiber: 5 },
  { id: 'dolma',             name: 'Dolma (3 pcs)',              cat: 'meal',    serving: 3,   unit: 'pcs', cal: 180, p: 4,  c: 22,   f: 8,    fiber: 3 },
  { id: 'warak-enab',        name: 'Warak Enab (3 pcs)',         cat: 'meal',    serving: 3,   unit: 'pcs', cal: 165, p: 3.5, c: 20, f: 7, fiber: 2.5 },
  { id: 'zaatar-bread',      name: 'Zaatar Manakish',            cat: 'meal',    serving: 1,   unit: 'piece', cal: 280, p: 7, c: 38,   f: 11,   fiber: 2 },
  { id: 'cheese-manakish',   name: 'Cheese Manakish',            cat: 'meal',    serving: 1,   unit: 'piece', cal: 340, p: 12, c: 34,  f: 17,   fiber: 1.5 },

  // ============== SOUTH ASIAN DISHES ==============
  { id: 'biryani-chicken',   name: 'Chicken Biryani (Plate)',    cat: 'meal',    serving: 1,   unit: 'plate', cal: 780, p: 35, c: 95, f: 28, fiber: 3 },
  { id: 'biryani-beef',      name: 'Beef Biryani (Plate)',       cat: 'meal',    serving: 1,   unit: 'plate', cal: 850, p: 38, c: 95, f: 34, fiber: 3 },
  { id: 'biryani-mutton',    name: 'Mutton Biryani (Plate)',     cat: 'meal',    serving: 1,   unit: 'plate', cal: 920, p: 40, c: 95, f: 42, fiber: 3 },
  { id: 'nihari',            name: 'Nihari (Bowl)',              cat: 'meal',    serving: 1,   unit: 'bowl', cal: 620, p: 42, c: 15, f: 42, fiber: 2 },
  { id: 'haleem',            name: 'Haleem (Bowl)',              cat: 'meal',    serving: 1,   unit: 'bowl', cal: 420, p: 24, c: 40, f: 18, fiber: 5 },
  { id: 'karahi-chicken',    name: 'Chicken Karahi (Plate)',     cat: 'meal',    serving: 1,   unit: 'plate', cal: 580, p: 38, c: 15, f: 40, fiber: 3 },
  { id: 'daal',              name: 'Daal (Bowl)',                cat: 'meal',    serving: 1,   unit: 'bowl', cal: 190, p: 12, c: 28, f: 3, fiber: 9 },
  { id: 'samosa',            name: 'Samosa (1 pc)',              cat: 'meal',    serving: 1,   unit: 'ea', cal: 260, p: 5,   c: 30,   f: 14,   fiber: 3 },
  { id: 'chicken-tikka',     name: 'Chicken Tikka (5 pcs)',      cat: 'meal',    serving: 5,   unit: 'pcs', cal: 300, p: 40, c: 4, f: 14, fiber: 0 },
  { id: 'butter-chicken',    name: 'Butter Chicken (Plate)',     cat: 'meal',    serving: 1,   unit: 'plate', cal: 620, p: 42, c: 15, f: 42, fiber: 2 },

  // ============== TURKISH DISHES ==============
  { id: 'iskender',          name: 'Iskender Kebap (Plate)',     cat: 'meal',    serving: 1,   unit: 'plate', cal: 820, p: 48, c: 55, f: 42, fiber: 3 },
  { id: 'adana',             name: 'Adana Kebap',                cat: 'meal',    serving: 1,   unit: 'skewer', cal: 520, p: 34, c: 15, f: 36, fiber: 1 },
  { id: 'lahmacun',          name: 'Lahmacun',                   cat: 'meal',    serving: 1,   unit: 'ea', cal: 320, p: 15, c: 38,   f: 12,   fiber: 2 },
  { id: 'manti',             name: 'Manti (Plate)',              cat: 'meal',    serving: 1,   unit: 'plate', cal: 520, p: 22, c: 60, f: 20, fiber: 3 },
  { id: 'pide',              name: 'Pide (Meat)',                cat: 'meal',    serving: 1,   unit: 'ea', cal: 540, p: 22, c: 58,   f: 22,   fiber: 3 },

  // ============== SE ASIAN / INDONESIAN / MALAYSIAN ==============
  { id: 'nasi-lemak',        name: 'Nasi Lemak (Plate)',         cat: 'meal',    serving: 1,   unit: 'plate', cal: 580, p: 22, c: 80, f: 20, fiber: 4 },
  { id: 'rendang',           name: 'Beef Rendang (Bowl)',        cat: 'meal',    serving: 1,   unit: 'bowl', cal: 520, p: 32, c: 10, f: 38, fiber: 2 },
  { id: 'satay-chicken',     name: 'Chicken Satay (5 skewers)',  cat: 'meal',    serving: 5,   unit: 'skewers', cal: 320, p: 30, c: 12, f: 18, fiber: 1 },
  { id: 'mee-goreng',        name: 'Mee Goreng',                 cat: 'meal',    serving: 1,   unit: 'plate', cal: 580, p: 18, c: 78, f: 20, fiber: 4 },

  // ============== WESTERN / FAST FOOD (HALAL-COMMON) ==============
  { id: 'burger-single',     name: 'Cheeseburger (Single)',      cat: 'meal',    serving: 1,   unit: 'ea', cal: 520, p: 28, c: 42, f: 26, fiber: 2 },
  { id: 'burger-double',     name: 'Double Cheeseburger',        cat: 'meal',    serving: 1,   unit: 'ea', cal: 780, p: 45, c: 42, f: 46, fiber: 2 },
  { id: 'pizza-slice',       name: 'Pizza (1 Slice)',            cat: 'meal',    serving: 1,   unit: 'slice', cal: 285, p: 12, c: 36, f: 10, fiber: 2 },
  { id: 'sub-sandwich',      name: 'Sub Sandwich (6")',          cat: 'meal',    serving: 1,   unit: 'ea', cal: 380, p: 22, c: 46, f: 10, fiber: 4 },
  { id: 'chipotle-bowl',     name: 'Chipotle Chicken Bowl',      cat: 'meal',    serving: 1,   unit: 'bowl', cal: 680, p: 50, c: 75, f: 18, fiber: 12 },
  { id: 'caesar-salad',      name: 'Caesar Salad (w/ Chicken)',  cat: 'meal',    serving: 1,   unit: 'bowl', cal: 420, p: 30, c: 12, f: 28, fiber: 4 },
  { id: 'nandos-1-4',        name: "Nando's 1/4 Chicken",        cat: 'meal',    serving: 1,   unit: 'ea', cal: 310, p: 40, c: 0, f: 16, fiber: 0 },

  // ============== SNACKS & SWEETS ==============
  { id: 'baklava',           name: 'Baklava (1 pc)',             cat: 'sweet',   serving: 1,   unit: 'pc', cal: 220, p: 3.5, c: 22,   f: 14,   fiber: 1 },
  { id: 'kunafa',            name: 'Kunafa (Slice)',             cat: 'sweet',   serving: 1,   unit: 'slice', cal: 380, p: 7, c: 42,  f: 20,   fiber: 1.5 },
  { id: 'luqaimat',          name: 'Luqaimat (5 pcs)',           cat: 'sweet',   serving: 5,   unit: 'pcs', cal: 280, p: 4, c: 38,    f: 13,   fiber: 1 },
  { id: 'halva',             name: 'Halva (1 oz)',               cat: 'sweet',   serving: 28,  unit: 'g', cal: 130, p: 3.5, c: 15,    f: 7,    fiber: 1 },
  { id: 'ice-cream',         name: 'Ice Cream (1 scoop)',        cat: 'sweet',   serving: 1,   unit: 'scoop', cal: 137, p: 2.3, c: 16, f: 7,   fiber: 0.5 },
  { id: 'chocolate-dark',    name: 'Dark Chocolate (1 sq)',      cat: 'sweet',   serving: 10,  unit: 'g', cal: 60, p: 0.8, c: 4.6,    f: 4.3,  fiber: 1 },
  { id: 'cookie',            name: 'Cookie (Chocolate Chip)',    cat: 'sweet',   serving: 1,   unit: 'ea', cal: 150, p: 2,  c: 20,    f: 7,    fiber: 0.5 },

  // ============== BEVERAGES ==============
  { id: 'coffee-black',      name: 'Coffee (Black)',             cat: 'drink',   serving: 240, unit: 'ml', cal: 2,  p: 0.3,  c: 0,    f: 0,    fiber: 0 },
  { id: 'coffee-milk',       name: 'Coffee with Milk',           cat: 'drink',   serving: 240, unit: 'ml', cal: 60, p: 3,    c: 5,    f: 3,    fiber: 0 },
  { id: 'latte',             name: 'Latte (Medium)',             cat: 'drink',   serving: 350, unit: 'ml', cal: 180, p: 10,  c: 18,   f: 7,    fiber: 0 },
  { id: 'cappuccino',        name: 'Cappuccino',                 cat: 'drink',   serving: 240, unit: 'ml', cal: 80, p: 5,    c: 7,    f: 4,    fiber: 0 },
  { id: 'tea-black',         name: 'Tea (Black)',                cat: 'drink',   serving: 240, unit: 'ml', cal: 2,  p: 0,    c: 0.5,  f: 0,    fiber: 0 },
  { id: 'tea-green',         name: 'Green Tea',                  cat: 'drink',   serving: 240, unit: 'ml', cal: 2,  p: 0,    c: 0,    f: 0,    fiber: 0 },
  { id: 'karak',             name: 'Karak Chai',                 cat: 'drink',   serving: 240, unit: 'ml', cal: 120, p: 4,   c: 18,   f: 4,    fiber: 0 },
  { id: 'mint-tea',          name: 'Moroccan Mint Tea',          cat: 'drink',   serving: 240, unit: 'ml', cal: 50, p: 0,    c: 12,   f: 0,    fiber: 0 },
  { id: 'orange-juice',      name: 'Orange Juice',               cat: 'drink',   serving: 240, unit: 'ml', cal: 112, p: 1.7, c: 26,   f: 0.5,  fiber: 0.5 },
  { id: 'smoothie',          name: 'Protein Smoothie',           cat: 'drink',   serving: 400, unit: 'ml', cal: 320, p: 30,  c: 35,   f: 6,    fiber: 5 },
];

// Helper to get foods by category
window.QAWI_FOODS_BY_CAT = window.QAWI_FOODS.reduce((acc, f) => {
  (acc[f.cat] = acc[f.cat] || []).push(f);
  return acc;
}, {});

window.QAWI_FOOD_CATEGORIES = [
  { id: 'protein', label: 'PROTEIN',  icon: '◆', color: '#e07b5f' },
  { id: 'carb',    label: 'CARBS',    icon: '▲', color: '#c9a84c' },
  { id: 'fat',     label: 'FATS',     icon: '●', color: '#7ab87a' },
  { id: 'meal',    label: 'MEALS',    icon: '◈', color: '#d65f5f' },
  { id: 'veg',     label: 'VEG',      icon: '▼', color: '#5fa8d6' },
  { id: 'fruit',   label: 'FRUIT',    icon: '◇', color: '#b07fd6' },
  { id: 'drink',   label: 'DRINKS',   icon: '○', color: '#6fb4c4' },
  { id: 'sweet',   label: 'SWEETS',   icon: '◉', color: '#d69cc9' },
  { id: 'supplement', label: 'SUPPS', icon: '◊', color: '#9b7fd6' },
];
